# Generated by Django 4.1.4 on 2022-12-14 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_order_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(default=datetime.date(2022, 12, 14), verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 12, 14), verbose_name='Дата начала'),
        ),
    ]
