# Generated by Django 4.1.4 on 2022-12-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_task_end_date_alter_task_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ManyToManyField(blank=True, null=True, related_name='Order_Employee', to='main.employee', verbose_name='Работники'),
        ),
        migrations.AlterField(
            model_name='project',
            name='employee',
            field=models.ManyToManyField(blank=True, null=True, related_name='Project_Employee', to='main.employee', verbose_name='Сотрудники'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.ManyToManyField(blank=True, null=True, related_name='Project_Order', to='main.order', verbose_name='Заказы'),
        ),
        migrations.AlterField(
            model_name='project',
            name='props',
            field=models.ManyToManyField(blank=True, null=True, related_name='Project_Props', to='main.props', verbose_name='Реквизит'),
        ),
    ]
