# Generated by Django 4.1.4 on 2022-12-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_order_employee_alter_project_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to="project's avatars", verbose_name='Аватарка'),
        ),
    ]
