# Generated by Django 4.1.4 on 2022-12-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='props',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Аватарка'),
        ),
    ]
