# Generated by Django 4.1.4 on 2023-01-09 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_props_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='datetime',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date(2023, 1, 9), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='realization',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
