# Generated by Django 4.1.4 on 2023-01-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_project_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.ManyToManyField(blank=True, null=True, related_name='Project_Order', to='main.order', verbose_name='order'),
        ),
    ]
